---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-tika
  namespace: ocis
  labels:
    app.kubernetes.io/name: ocis
    app.kubernetes.io/instance: ocis
    app.kubernetes.io/component: tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ocis
      app.kubernetes.io/instance: ocis
      app.kubernetes.io/component: tika
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ocis
        app.kubernetes.io/instance: ocis
        app.kubernetes.io/component: tika
    spec:
      containers:
        - name: tika
          image: docker.io/apache/tika:3.2.3.0-full
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9998
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: "-Xmx3g"
          resources:
            limits:
              cpu: 1000m
              memory: 3Gi
            requests:
              cpu: 100m
              memory: 1Gi
