---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg
  - flux-system
  - kube-prometheus-stack
  - loki
  - mimir
  - minio
  - prometheus-smartctl-exporter
  - promtail
  - rook-ceph
  - namespace.yaml
