---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - kube-prometheus-stack
  - loki
  - prometheus-blackbox-exporter
  - prometheus-smartctl-exporter
  - promtail
  - namespace.yaml
