---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=kubevirt/kubevirt
  - https://github.com/kubevirt/kubevirt/releases/download/v1.7.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v1.7.0/kubevirt-cr.yaml
