---
apiVersion: v1
kind: Service
metadata:
  name: outline-server
  namespace: outline
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: outline
    app.kubernetes.io/instance: outline
spec:
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: outline
    app.kubernetes.io/instance: outline
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
