---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iframely
  namespace: iframely
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/component: iframely
    app.kubernetes.io/name: iframely
    app.kubernetes.io/instance: iframely
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: iframely
      app.kubernetes.io/name: iframely
      app.kubernetes.io/instance: iframely
  template:
    metadata:
      labels:
        app.kubernetes.io/component: iframely
        app.kubernetes.io/name: iframely
        app.kubernetes.io/instance: iframely
    spec:
      containers:
        - name: iframely
          image: jolt/iframely:v2.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8061
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 8061
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8061
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: 8061
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1024Mi
          volumeMounts:
            - name: iframely-config
              mountPath: /app/config/config.local.js
              subPath: config.local.js
      volumes:
        - name: iframely-config
          configMap:
            name: iframely-config
