---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - persistentvolumeclaim.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.sops.yaml
  - service.yaml
  - serviceaccount.yaml
