---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg.yaml
  - csi-driver-nfs.yaml
  - descheduler.yaml
  - falcosecurity.yaml
  - gitlab.yaml
  - grafana.yaml
  - ingress-nginx.yaml
  - metrics-server.yaml
  - minio-community.yaml
  - minio.yaml
  - rook-release.yaml
  - unpoller.yaml
