---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg.yaml
  - csi-driver-nfs.yaml
  - descheduler.yaml
  - falcosecurity.yaml
  - gitlab.yaml
  - grafana.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - metallb.yaml
  - metrics-server.yaml
  - minio-community.yaml
  - minio.yaml
  - prometheus-community.yaml
  - rook-release.yaml
  - stakater.yaml
  - unpoller.yaml
  - vmware-tanzu.yaml
