---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - cloudnative-pg.yaml
  - coredns.yaml
  - falcosecurity.yaml
  - gitlab.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - metrics-server.yaml
  - oauth2-proxy.yaml
  - prometheus-community.yaml
  - vmware-tanzu.yaml
