---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudnative-pg
  - dragonfly-operator
  - external-snapshotter
  - keycloak
  - kube-prometheus-stack
  - plugin-barman-cloud
  - velero
