---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-tags depName=kubernetes-csi/external-snapshotter
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/refs/tags/v8.5.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
  - https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/refs/tags/v8.5.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
