---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cdi
  namespace: flux-system
spec:
  dependsOn:
    - name: kubevirt
  interval: 1h
  path: ./apps/cdi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
