---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
  interval: 1h
  path: ./apps/external-snapshotter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
