---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iframly
  namespace: flux-system
spec:
  interval: 1h
  path: ./apps/iframely
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
