---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - coredns.yaml
  - crds.yaml
  - ingress-nginx.yaml
  - metrics-server.yaml
  - rook-ceph.yaml
