---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - coredns.yaml
  - crds.yaml
  - dragonfly-operator.yaml
  - falco.yaml
  - iframely.yaml
  - ingress-nginx.yaml
  - keycloak.yaml
  - minio-operator.yaml
  - metrics-server.yaml
  - monitoring.yaml
  - reloader.yaml
  - rook-ceph.yaml
  - stirling-pdf.yaml
  - vaultwarden.yaml
  - velero.yaml
