---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bentopdf.yaml
  - cdi.yaml
  - cert-manager.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - coredns.yaml
  - crds.yaml
  - csi-driver-nfs.yaml
  - descheduler.yaml
  - dragonfly-operator.yaml
  - drawio.yaml
  - external-snapshotter.yaml
  - falco.yaml
  - gitlab.yaml
  - iframely.yaml
  - ingress-nginx.yaml
  - keycloak.yaml
  - kubevirt.yaml
  - metrics-server.yaml
  - mimir.yaml
  - minio-backup.yaml
  - minio-operator.yaml
  - monitoring.yaml
  - multus.yaml
  - node-feature-discovery.yaml
  - ocis.yaml
  - outline.yaml
  - reloader.yaml
  - renovate.yaml
  - rook-ceph.yaml
  - spegel.yaml
  - vaultwarden.yaml
  - velero.yaml
