---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: grafana-dashboard-ceph-cluster
    namespace: rook-ceph
    files:
      - ceph-cluster-dashboard.json=https://raw.githubusercontent.com/rook/rook/refs/heads/master/deploy/examples/monitoring/grafana/Ceph%20Cluster%20Dashboard.json
  - name: grafana-dashboard-ceph-single
    namespace: rook-ceph
    files:
      - ceph-single-dashboard.json=https://raw.githubusercontent.com/rook/rook/refs/heads/master/deploy/examples/monitoring/grafana/Ceph%20OSD%20Single%20Dashboard.json
  - name: grafana-dashboard-ceph-pools
    namespace: rook-ceph
    files:
      - ceph-pools-dashboard.json=https://raw.githubusercontent.com/rook/rook/refs/heads/master/deploy/examples/monitoring/grafana/Ceph%20Pools%20Dashboard.json
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
