apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-grafana-sso
  namespace: monitoring
type: Opaque
stringData:
  GRAFANA_AUTH_CLIENT_ID: ENC[AES256_GCM,data:ykCb/nporA==,iv:vv36rcbqciCoKd50uuzyltBYo3A7+O1uGbtbqhrVU7Y=,tag:8zLuQYnWct/WYhXaVgMYoQ==,type:str]
  GRAFANA_AUTH_CLIENT_SECRET: ENC[AES256_GCM,data:wuB4jBvXlMKslf+lJPjDo6TAISV9EluoaU6SZlM7X2g=,iv:vhfRDAhSvhrZCxNUGULiYanpFWqM2csoKtxuhI3lRcM=,tag:7mAYksCFWI3hLw4LsZP2iA==,type:str]
sops:
  age:
    - recipient: age1etdt8rdcykvfu5q4f8t3vp4uxg3c03xlh4l98egdfdluslfxeaks25angd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbmRnWXJrd3FMSHk5S0Rr
        S2Q0aENXcVNjTk1zQjdlV21tanJyY2kxU0dZClpZYTc3UE5NQlVHZGlPNVNMS3V4
        OGZ0aDR6MHNqcnovOGlwaDFURS9sZkUKLS0tIGhSZXJ1c0FVd1BUYTY2bTZ4SWtR
        S0FzMEFoWVhoSmJhMUtSQnIwRTYySzAKmlrQigoHpWXEvOtkTwDG88RdbCRwzvPc
        zd6UDR5c9BVQBaVwmwl60TDaq/frJT7Xd6uT1YnF8uBIFQEeSBfSnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-17T14:30:37Z"
  mac: ENC[AES256_GCM,data:j1IP/+KxFZ8zC1BkxIdLCGmYrGiDhxI/25EQkUoy/xjGW4Cmjdvyo9iU3uUp9gvXbdOZc/7ErrBfG8j72Tuhatd4dOjiBQTL/oefmBFGwWZb0ZEXhKdsNggZQsKgfSJmLChVvbb5Zr6c2d3R13OmUAJczI93naILNv50OpPaDFo=,iv:0yn85Mp7I5kWmR8tAxxN7KTxQwRFrs5t9mv0muuay0k=,tag:m9pxSbtjmS6l/9UJ3ui2VQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
